export class AppCodes {
  // Add other domains in the future, e.g. UI_FLOW, VALIDATOR, SAVE_SYSTEM.
  static YAML_READ = Object.freeze({
    OK: "OK",
    INVALID_PATH: "INVALID_PATH",
    INVALID_EXTENSION: "INVALID_EXTENSION",
    FILE_NOT_FOUND: "FILE_NOT_FOUND",
    NOT_A_FILE: "NOT_A_FILE",
    READ_FAILED: "READ_FAILED",
    EMPTY_FILE: "EMPTY_FILE",
    PARSE_FAILED: "PARSE_FAILED",
    EMPTY_CONTENT: "EMPTY_CONTENT",
    TYPE_MISMATCH: "TYPE_MISMATCH",
    VALIDATION_FAILED: "VALIDATION_FAILED",
    UNKNOWN_ERROR: "UNKNOWN_ERROR"
  });

  static COMMON = Object.freeze({
    INVALID_ARGUMENT: "INVALID_ARGUMENT",
    EXPECTED_OBJECT: "EXPECTED_OBJECT",
    EXPECTED_ARRAY: "EXPECTED_ARRAY",
    EMPTY_ID: "EMPTY_ID",
    DUPLICATE_ID: "DUPLICATE_ID",
    ALIAS_CYCLE: "ALIAS_CYCLE",
    ASSERT_FAILED: "ASSERT_FAILED"
  });

  static REGISTRY = Object.freeze({
    NOT_LOADED: "NOT_LOADED",
    INVALID_ROOT: "INVALID_ROOT",
    INVALID_PAGES: "INVALID_PAGES",
    INVALID_ALIASES: "INVALID_ALIASES",
    PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
    SCENE_PATH_MISSING: "SCENE_PATH_MISSING"
  });

  static FLOW = Object.freeze({
    NOT_LOADED: "NOT_LOADED",
    INVALID_ROOT: "INVALID_ROOT",
    INVALID_FLOW_META: "INVALID_FLOW_META",
    INVALID_NODES: "INVALID_NODES",
    ENTRY_NOT_FOUND: "ENTRY_NOT_FOUND",
    NODE_NOT_FOUND: "NODE_NOT_FOUND",
    INVALID_TRANSITIONS: "INVALID_TRANSITIONS",
    INVALID_TRANSITION_TARGET: "INVALID_TRANSITION_TARGET",
    TRANSITION_PRESET_NOT_FOUND: "TRANSITION_PRESET_NOT_FOUND"
  });

  static SCENE = Object.freeze({
    NOT_LOADED: "NOT_LOADED",
    INVALID_ROOT: "INVALID_ROOT",
    INVALID_SCENE: "INVALID_SCENE",
    INVALID_COMPONENTS: "INVALID_COMPONENTS",
    NODE_NOT_FOUND: "NODE_NOT_FOUND",
    PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
    SCENE_PATH_NOT_FOUND: "SCENE_PATH_NOT_FOUND",
    THEME_NOT_LOADED: "THEME_NOT_LOADED"
  });

  static RENDERER = Object.freeze({
    ROOT_NOT_MOUNTED: "ROOT_NOT_MOUNTED",
    DOM_UNAVAILABLE: "DOM_UNAVAILABLE",
    INVALID_SCENE: "INVALID_SCENE",
    INVALID_COMPONENT: "INVALID_COMPONENT",
    UNSUPPORTED_COMPONENT_TYPE: "UNSUPPORTED_COMPONENT_TYPE",
    ACTION_DISPATCHER_MISSING: "ACTION_DISPATCHER_MISSING",
    LAYER_NOT_FOUND: "LAYER_NOT_FOUND"
  });

  static BUS = Object.freeze({
    INVALID_CHANNEL: "INVALID_CHANNEL",
    INVALID_LISTENER: "INVALID_LISTENER"
  });

  static VALIDATOR = Object.freeze({
    NOT_READY: "NOT_READY",
    ENTRY_NOT_FOUND: "ENTRY_NOT_FOUND",
    NODE_NOT_FOUND: "NODE_NOT_FOUND",
    PAGE_NOT_FOUND: "PAGE_NOT_FOUND",
    VALIDATION_FAILED: "VALIDATION_FAILED"
  });

  static RUNTIME = Object.freeze({
    NOT_READY: "NOT_READY",
    NOT_STARTED: "NOT_STARTED",
    NODE_NOT_FOUND: "NODE_NOT_FOUND",
    INVALID_ACTION: "INVALID_ACTION"
  });

  static BOOTSTRAP = Object.freeze({
    NOT_READY: "NOT_READY",
    INIT_FAILED: "INIT_FAILED"
  });
}

// Compatibility export for current callers.
export const YamlReadCode = AppCodes.YAML_READ;
export const CommonCode = AppCodes.COMMON;
export const RegistryCode = AppCodes.REGISTRY;
export const FlowCode = AppCodes.FLOW;
export const SceneCode = AppCodes.SCENE;
export const RendererCode = AppCodes.RENDERER;
export const BusCode = AppCodes.BUS;
export const ValidatorCode = AppCodes.VALIDATOR;
export const RuntimeCode = AppCodes.RUNTIME;
export const BootstrapCode = AppCodes.BOOTSTRAP;
